// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq7NcnZCYjrNWwFwu3yvxRtqdEdGQtg-U',
    appId: '1:754295610315:web:59154f36f81fd97cd0344e',
    messagingSenderId: '754295610315',
    projectId: 'task-8f552',
    authDomain: 'task-8f552.firebaseapp.com',
    storageBucket: 'task-8f552.firebasestorage.app',
    measurementId: 'G-NX7Z2ZV0HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFwO7ZP9zprgBZ50ep5JZmSzRoC1HbVEc',
    appId: '1:754295610315:android:92ef41b4c72505f9d0344e',
    messagingSenderId: '754295610315',
    projectId: 'task-8f552',
    storageBucket: 'task-8f552.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVDaepGRn4t-5OkDShNTErzNcZiLk7t5g',
    appId: '1:754295610315:ios:24a0b75a72a253e2d0344e',
    messagingSenderId: '754295610315',
    projectId: 'task-8f552',
    storageBucket: 'task-8f552.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVDaepGRn4t-5OkDShNTErzNcZiLk7t5g',
    appId: '1:754295610315:ios:24a0b75a72a253e2d0344e',
    messagingSenderId: '754295610315',
    projectId: 'task-8f552',
    storageBucket: 'task-8f552.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq7NcnZCYjrNWwFwu3yvxRtqdEdGQtg-U',
    appId: '1:754295610315:web:0d5e1d772876123dd0344e',
    messagingSenderId: '754295610315',
    projectId: 'task-8f552',
    authDomain: 'task-8f552.firebaseapp.com',
    storageBucket: 'task-8f552.firebasestorage.app',
    measurementId: 'G-YNL7N52R3S',
  );
}
